### PR TITLE
Make the readme actually contain stuff, what a concept

### PR DESCRIPTION
**Pull request by TheTechRobo**
nah i'm bad at documentation too
fixes overlisted#1

### CODE REVIEW

**Comment by overlisted** [comment]
i should also probably add a self hosting section but whatever

**Comment by TheTechRobo** [comment]
isn't it just like `npm i` then `npm bot.js` or am i stupid

**Comment by overlisted** [comment]
no

**Comment by TheTechRobo** [comment]
ok im stupid

**Pull request merged**
